### PR TITLE
implement U and V wind components for partial sums.

### PR DESCRIPTION
**Pull request by randytpierce**
used metpy to impment the U and V components in the sums

### CODE REVIEW

**Comment by randytpierce** [comment]
Please check the algorithm for calculating U and V. I had to subtract 180 form the wind directions for HRRR but I don't know if it will be required for all the models.

**Review by ian-noaa — COMMENTED** [review]
I'll leave it to Molly & Jeff to validate the calculation. However, this seems logical. My only critique would be to recommend adding a comment explaining that reversing the wind direction (`model_elem["WD"]- 180`) was required due to the HRRR data. That way it's easier to know if it can be removed/modified or if we need to add a special case for other models. 

It'd be interesting to know why the HRRR (or the metpy function) report the wind direction in reverse. I seem to recall wind direction can be inverted from what you'd normally anticipate due to different conventions/frames of reference but forget the specifics.

**Comment by mollybsmith-noaa** [comment]
@ian-noaa to clarify, it's not a reversal of wind direction, it's a coordinate adjustment that sometimes has to be done in models. The HRRR output and METAR give wind direction in a range of 0-360 degrees, while that metpy function expects inputs with a range of -180 to 180 degrees. It's the same value, it's just been transformed to different coordinates. This happens frequently with longitude as well. Some models give it as 0-360, some as -180 to 180, and the use has to just choose the one they want to work with and then adjust the others to that grid system. Does that make sense?

**Review by mollybsmith-noaa — APPROVED** [review]

**Review by randytpierce — COMMENTED** [review]
Added a comment as suggested

**Comment by randytpierce** [comment]
created comment as suggested

**Comment by ian-noaa** [comment]
Thanks Molly! That makes more sense that it's a transformation. We were running into some stuff in Unified Graphics where the directionality was reversed from what we were expecting. It made sense once we shifted the frame of reference. This is much easier!

Do model output & observations typically run 0-360 degrees for NOAA instead of -180 to 180 degrees? Or is it just coincidence that METARs & HRRR output have the same range?

**Pull request merged**
